# Generated by Django 4.1.2 on 2022-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('class_1', models.CharField(max_length=30)),
                ('class_2', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=300)),
                ('objective', models.CharField(max_length=300)),
                ('q_digit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaskString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeightSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.DecimalField(decimal_places=3, max_digits=5)),
                ('class_1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('class_2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('abilities', models.DecimalField(decimal_places=3, max_digits=5)),
                ('objective', models.DecimalField(decimal_places=3, max_digits=5)),
                ('calc_type', models.CharField(choices=[('CONCAT', 'concat'), ('AVG', 'average')], default='CONCAT', max_length=20)),
            ],
        ),
    ]
