# Generated by Django 4.1.2 on 2022-10-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightsetup',
            name='calc_type',
        ),
    ]
