# Generated by Django 4.1.2 on 2022-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_weightsetup_calc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONCAT', 'concat'), ('AVG', 'average')], default='CONCAT', max_length=20)),
            ],
        ),
    ]
