# Generated by Django 4.1.2 on 2022-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_abilitytype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbilityType',
        ),
        migrations.AddField(
            model_name='weightsetup',
            name='type',
            field=models.CharField(choices=[('CONCAT', 'concat'), ('AVG', 'average')], default='CONCAT', max_length=20),
        ),
    ]
